# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/taker/my_mano/my_mano.cache/wt [current_project]
set_property parent.project_path C:/Users/taker/my_mano/my_mano.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/taker/my_mano/my_mano.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/AC_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/ALU.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/AR_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/BIT_COUNTER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/BUS_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/BUS_SELECTION.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/CONTROLER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/DECODER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/DECODER3_8.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/DR_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/ENCODER8_3.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/INSTRUCTION_REGISTER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/IR-DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/MEMORY_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/PC_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/PROGRAM_COUNTER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/SC_DESIGN.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/SequenceCounter.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/T_COUNTER.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/memory.v
  C:/Users/taker/my_mano/my_mano.srcs/sources_1/new/ARCHITECTURE.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ARCHITECTURE -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ARCHITECTURE.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ARCHITECTURE_utilization_synth.rpt -pb ARCHITECTURE_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
